@startuml

interface src.backend.model.Figure{
    +   {static} int OFFSET = 10
    .. getters ..
    +   double getLeft()
    +   double getTop()
    +   double getHeight()
    +   double getWidth()
    +   Point getCenter()
.. Other methods ..
    +   boolean belongs(Point eventPoint)
    +   void move(double diffX, double diffY)
    +   Figure duplicate()
    +   Pair<Figure,Figure> split()
}
class src.backend.model.Ellipse implements src.backend.model.Figure{
    #   Point centerPoint
    -   double sMayorAxis
    -   double sMinorAxis
    +   Ellipse(Point centerPoint, double sMayorAxis, double sMinorAxis)
    .. getters ..
    +   Point getCenterPoint()
    +   double getsMayorAxis()
    +   double getsMinorAxis()
    +   String toString()
}
class src.backend.model.Circle extends src.backend.model.Ellipse{
    +   Circle(Point centerPoint, double radius)
    .. getters ..
    +   double getRadius()
}
class src.backend.model.Rectangle implements src.backend.model.Figure{
    -   Point topLeft
    -   Point bottomRight
    +   Rectangle(Point topLeft, Point bottomRight)
    .. getters ..
    +   Point getTopLeft()
    +   Point getBottomRight()
    +   String toString()
}
class src.backend.model.Square extends src.backend.model.Rectangle{
    -   double size
    +   Square(Point topLeft, double size)
}
class src.backend.model.Point{
    -   double x
    -   double y
    .. getters ..
    +   double getX()
    +   double getY()
    +   double getDistanceX(Point point)
    +   double getDistanceY(Point point)
    +   String toString()
    .. setters ..
    +   void setX(double x)
    +   void setY(double y)
}
Ellipse::centerPoint *-right- Point : contains
Rectangle::topLeft *-left- Point : contains
Rectangle::bottomRight *-left- Point : contains
class src.frontend.main.AppLauncher extends javafx.application.Application{
    + void main(String[] args)
    --
    + void start(Stage primaryStage)
}
class src.frontend.main.MainFrame extends javafx.scene.layout.VBox{
    +   MainFrame(SortedMap<Layer, Pair<Boolean, CanvasState>> layersMap)}
}
class src.frontend.main.AppMenuBar extends javafx.scene.control.MenuBar{
    +   AppMenuBar()
}
enum src.frontend.properties.BorderEnum{
    NORMAL
    PUNTEADO_SIMPLE
    PUNTEADO_COMPLEJO
    -   choiceName
    +   String toString()
    +   void setPattern(GraphicsContext gc)
}
interface java.lang.Comparable<T>
class src.frontend.properties.Layer implements java.lang.Comparable<Layer>{
    -   int layer
    +   Layer(int layer)
    +   int getLayer()
    +   String toString()
    +   int compareTo(Layer o)
    +   boolean equals(Object o)
}
class src.frontend.panes.LayersPane extends javafx.scene.layout.BorderPane{
    -   int layerCount = 3
    .. ButtonsBox ..
    -   ChoiceBox<Layer> capas
    -   RadioButton mostrarButton
    -   RadioButton ocultarButton
    -   Button addLayer
    -   Button removeLayer
--
    +   LayersPane()
    .. getters ..
    +   ChoiceBox<Layer> getChoiceLayer()
    +   RadioButton getMostrarButton()
    +   RadioButton getOcultarButton()
    +   Button getAddLayerButton()
    +   Button getRemoveLayerButton()
    +   int nextLayer()
}
class src.frontend.properties.Properties{
    -   Pair<Color, Color> colors
    -   ShadowEnum figureShadow
    -   BorderEnum figureBorderStyle
    -   double figureBorderWidth
    -   Layer figureLayer
    -   Set<String> tags
    +   Properties(Color c1, Color c2, ShadowEnum figureShadow, BorderEnum figureBorderStyle, double figureBorderWidth, Layer figureLayer)
    ..Setters..
    +   void setTags(String tagsToAdd)
    +   void setColors(Color c1, Color c2)
    +   void setFigureBorderStyle(BorderEnum figureBorderStyle)
    +   void setFigureBorderWidth(double figureBorderWidth)
    +   void setFigureShadow(ShadowEnum figureShadow)
    ..Getters..
    +   Set<String> getTags()
    +   Pair<Color, Color> getColors()
    +   ShadowEnum getFigureShadow()
    +   BorderEnum getFigureBorderStyle()
    +   double getFigureBorderWidth()
    +   Layer getFigureLayer()
}
enum src.frontend.properties.ShadowEnum{
    SIMPLE
    COLOREADA
    SIMPLE_INVERSA
    COLOREADA_INVERSA
    NINGUNA
    -   int offset
    -   String choiceName
    #   void shadowRecGen(GraphicsContext gc, Figure figure, Color color)
    #   void shadowRoundGen(GraphicsContext gc, Figure figure, Color color)
    +   String toString()
    +   void shadowRec(GraphicsContext gc, Figure figure,Color c)
    +   void shadowRound(GraphicsContext gc, Figure figure,Color c)
}
class src.frontend.panes.StatusPane extends javafx.scene.layout.BorderPane{
    -   Label statusLabel
    +   StatusPane()
    +   void updateStatus(String text)
}
class src.frontend.panes.PaintPane extends javafx.scene.layout.BorderPane{
    .. panes ..
    +   LayersPane layersPane
    +   LabelsPane labelPane
    +   StatusPane statusPane
    +   SortedMap<Layer, Pair<Boolean, ArrayList<FrontFigure>>> layerPairSortedMap
    +   Canvas canvas
    +   GraphicsContext gc
    +   Color lineColor
    +   Color defaultFillColor1
    +   Color defaultFillColor2
    +   ToggleButton selectionButton
    +   FigureButton rectangleButton
    +   FigureButton circleButton
    +   FigureButton squareButton
    +   FigureButton ellipseButton
    +   ToggleButton deleteButton
    +   ObservableList<ShadowEnum> shadowsOptions
    +   ChoiceBox<ShadowEnum> shadows
    +   ColorPicker fillColorPicker1
    +   ColorPicker fillColorPicker2
    +   Slider edgeSlider
    +   ObservableList<BorderEnum> borderOptions
    +   ChoiceBox<BorderEnum> borders
    +   Button duplicarButton
    +   Button dividirButton
    +   Button movCentroButton
    +   Button guardarButton
    +   TextArea etiquetasDeForma
    +   Point startPoint
    +   FrontFigure selectedFigure
    -   double MAX=10
    -   double MIN=0.00000001
    --
    +   PaintPane(SortedMap<Layer, Pair<Boolean, ArrayList<FrontFigure>>> canvasState, StatusPane statusPane, LabelsPane labelPane,LayersPane layersPane)
    -   void redrawCanvas()
    -   void deleteFigure(FrontFigure figure)
}
interface src.frontend.front_figures.Drawable{
    +   void drawEdge(GraphicsContext gc)
    +   void draw(GraphicsContext gc)
    +   Properties getProperties()
}
abstract class src.frontend.front_figures.FrontFigure implements src.frontend.front_figures.Drawable{
    #   Figure figure
    #   Properties properties
    +   FrontFigure(Figure figure, Properties properties)
    +   void setProperties(Properties properties)
    +   Boolean belongs(Point point)
    +   void move(double diffX,double diffY)
    +   Point getCenter()
    +   Pair<FrontFigure,FrontFigure> split()
    +   Properties copyProperties()
    +   public FrontFigure duplicate()
}
src.backend.model.Figure --* src.frontend.front_figures.FrontFigure::figure
src.frontend.properties.Properties --* src.frontend.front_figures.FrontFigure::properties
abstract class src.frontend.front_figures.FrontRectangularFigure extends src.frontend.front_figures.FrontFigure{
    +   FrontRectangularFigure(Figure figure, Properties properties)
}
abstract class src.frontend.front_figures.FrontOvalFigure extends src.frontend.front_figures.FrontFigure{
    +   FrontOvalFigure(Figure figure, Properties properties)
}
class src.frontend.front_figures.FrontRectangle extends src.frontend.front_figures.FrontRectangularFigure{
    +   FrontRectangle(Figure figure, Properties properties)
    +   FrontRectangle(Point topLeft, Point bottomRight, Properties properties)
}
class src.frontend.front_figures.FrontSquare extends src.frontend.front_figures.FrontRectangularFigure{
    +   FrontSquare(Figure figure, Properties properties)
    +   FrontSquare(Point topLeft, double size, Properties properties)
}
class src.frontend.front_figures.FrontCircle extends src.frontend.front_figures.FrontOvalFigure{
    +   FrontCircle(Figure figure, Properties properties)
    +   FrontCircle(Point centerPoint, double radius, Properties properties)
}
class src.frontend.front_figures.FrontEllipse extends src.frontend.front_figures.FrontOvalFigure{
    +   FrontElipse(Figure figure, Properties properties)
    +   FrontElipse(Point centerPoint, double sMayorAxis, double sMinorAxis, Properties properties)
}
class src.frontend.panes.button_types.FigureButton extends javafx.scene.control.ToggleButton{
    -   FigureButtonFunctionality fbf
    +   FigureButton(String name, FigureButtonFunctionality fbf)
    +   FrontFigure makeFrontFigure( Point endPoint, Point startPoint, Properties properties)
}
enum src.frontend.panes.button_types.FigureButtonFunctionality{
    CICLE_BUTTON
    ELLIPSE_BUTTON
    RECTANGLE_BUTTON
    SQUARE_BUTTON
    +   FrontFigure makeNewFigure( Point endPoint, Point startPoint, Properties properties)
}

@enduml