@startuml

interface src.backend.model.Figure{
    +   {static} int OFFSET = 10
    .. getters ..
    +   double getLeft()
    +   double getTop()
    +   double getHeight()
    +   double getWidth()
    +   Point getCenter()
.. Other methods ..
    +   boolean belongs(Point eventPoint)
    +   void move(double diffX, double diffY)
    +   Figure duplicate()
    +   Pair<Figure,Figure> split()
}
class src.backend.model.Ellipse implements src.backend.model.Figure{
    #   Point centerPoint
    -   double sMayorAxis
    -   double sMinorAxis
    +   Ellipse(Point centerPoint, double sMayorAxis, double sMinorAxis)
    .. getters ..
    +   Point getCenterPoint()
    +   double getsMayorAxis()
    +   double getsMinorAxis()
    +   String toString()
}
class src.backend.model.Circle extends src.backend.model.Ellipse{
    +   Circle(Point centerPoint, double radius)
    .. getters ..
    +   double getRadius()
}
class src.backend.model.Rectangle implements src.backend.model.Figure{
    -   Point topLeft
    -   Point bottomRight
    +   Rectangle(Point topLeft, Point bottomRight)
    .. getters ..
    +   Point getTopLeft()
    +   Point getBottomRight()
    +   String toString()
}
class src.backend.model.Square extends src.backend.model.Rectangle{
    -   double size
    +   Square(Point topLeft, double size)
}
class src.backend.model.Point{
    -   double x
    -   double y
    .. getters ..
    +   double getX()
    +   double getY()
    +   double getDistanceX(Point point)
    +   double getDistanceY(Point point)
    +   String toString()
    .. setters ..
    +   void setX(double x)
    +   void setY(double y)
}
Ellipse::centerPoint *-right- Point : contains
Rectangle::topLeft *-left- Point : contains
Rectangle::bottomRight *-left- Point : contains
class src.frontend.main.AppLauncher extends javafx.application.Application{
    + void main(String[] args)
    --
    + void start(Stage primaryStage)
}
class src.frontend.main.MainFrame extends javafx.scene.layout.VBox{
    +   MainFrame(SortedMap<Layer, Pair<Boolean, CanvasState>> layersMap)}
}
class src.frontend.main.AppMenuBar extends javafx.scene.control.MenuBar{
    +   AppMenuBar()
}
enum src.frontend.properties.BorderEnum{
    NORMAL
    PUNTEADO_SIMPLE
    PUNTEADO_COMPLEJO
    +   String toString()
    +   void setPattern(GraphicsContext gc)
}
interface java.lang.Comparable<T>
class src.frontend.properties.Layer implements java.lang.Comparable<Layer>{
    -   int layer
    +   Layer(int layer)
    +   int getLayer()
    +   String toString()
    +   int compareTo(Layer o)
    +   boolean equals(Object o)
}
class src.frontend.panes.LayersPane extends javafx.scene.layout.BorderPane{
    -   int layerCount = 3
    .. ButtonsBox ..
    -   ChoiceBox<Layer> capas
    -   RadioButton mostrarButton
    -   RadioButton ocultarButton
    -   Button addLayer
    -   Button removeLayer
--
    +   LayersPane()
    .. getters ..
    +   ChoiceBox<Layer> getChoiceLayer()
    +   RadioButton getMostrarButton()
    +   RadioButton getOcultarButton()
    +   Button getAddLayerButton()
    +   Button getRemoveLayerButton()
    +   int nextLayer()
}
class src.frontend.properties.Properties{
    -   Pair<Color, Color> colors
    -   ShadowEnum figureShadow
    -   BorderEnum figureBorderStyle
    -   double figureBorderWidth
    -   Layer figureLayer
    +   Properties(Color c1,Color c2,ShadowEnum figureShadow,BorderEnum figureBorder,double width,Layer figureLayer)
    ..Setters..
    +   Properties setColors(Color c1, Color c2)
    +   Properties setFigureBorderStyle(BorderEnum figureBorderStyle)
    +   Properties setFigureBorderWidth(double figureBorderWidth)
    +   Properties setFigureShadow(ShadowEnum figureShadow)
    ..Getters..
    +   Pair<Color, Color> getColors()
    +   ShadowEnum getFigureShadow()
    +   Pair<BorderEnum, Double> getFigureBorder()
    +   Layer getFigureLayer()
}
enum src.frontend.properties.ShadowEnum{
    SIMPLE
    COLOREADA
    SIMPLE_INVERSA
    COLOREADA_INVERSA
    NINGUNA
    -   int offset
    #   void shadowRecGen(GraphicsContext gc, Figure figure, Color color)
    #   void shadowRoundGen(GraphicsContext gc, Figure figure, Color color)
    +   String toString()
    +   void shadowRec(GraphicsContext gc, Figure figure,Color c)
    +   shadowRound(GraphicsContext gc, Figure figure,Color c)
}
class src.frontend.panes.StatusPane extends javafx.scene.layout.BorderPane{
    -   Label statusLabel
    +   StatusPane()
    +   void updateStatus(String text)
}
class src.frontend.panes.PaintPane extends javafx.scene.layout.BorderPane{
    .. panes ..
    +   LayersPane layersPane
    +   StatusPane statusPane
    +   SortedMap<Layer, Pair<Boolean, CanvasState>> layerPairSortedMap
    +   Canvas canvas
    +   GraphicsContext gc
    +   Color lineColor
    +   Color defaultFillColor1
    +   Color defaultFillColor2
    +   ToggleButton selectionButton
    +   ToggleButton rectangleButton
    +   ToggleButton circleButton
    +   ToggleButton squareButton
    +   ToggleButton ellipseButton
    +   ToggleButton deleteButton
    +   ObservableList<ShadowEnum> shadowsOptions
    +   ChoiceBox<ShadowEnum> shadows
    +   ColorPicker fillColorPicker1
    +   ColorPicker fillColorPicker2
    +   Slider edgeSlider
    +   ObservableList<BorderEnum> borderOptions
    +   ChoiceBox<BorderEnum> borders
    +   Button duplicarButton
    +   Button dividirButton
    +   Button movCentroButton
    +   Point startPoint
    +   Figure selectedFigure
    +   Map<Figure, Properties> figureProperties
    --
    +   PaintPane(SortedMap<Layer, Pair<Boolean, CanvasState>> canvasState, StatusPane statusPane, LayersPane layersPane)
    -   void redrawCanvas()
    -   void propertiesCopy(Figure source, Figure destiny)
    -   boolean figureBelongs(Figure figure, Point eventPoint)
    -   void deleteFigure(Figure figure)
    -   void drawRectangularFigure(Figure figure)
    -   void drawOvalFigure(Figure figure)
    -   void drawEdgeFigure(Figure figure)
}
interface src.frontend.front_figures.Drawable{
    +   void drawEdge(GraphicsContext gc)
    +   void draw(GraphicsContext gc)
    +   Properties getProperties()
}
abstract class src.frontend.front_figures.FrontFigure implements src.frontend.front_figures.Drawable{
    #   Figure figure
    #   Properties properties
    +   void setProperties(Properties properties)
    +   Boolean belongs(Point point)
    +   void move(double diffX,double diffY)
    +   Pair<FrontFigure,FrontFigure> split()
}
src.backend.model.Figure --* src.frontend.front_figures.FrontFigure::figure
src.frontend.properties.Properties --* src.frontend.front_figures.FrontFigure::properties
abstract class src.frontend.front_figures.FrontRectangularFigure extends src.frontend.front_figures.FrontFigure{
}
abstract class src.frontend.front_figures.FrontOvalFigure extends src.frontend.front_figures.FrontFigure{
}
class src.frontend.front_figures.FrontRectangle extends src.frontend.front_figures.FrontRectangularFigure{
}
class src.frontend.front_figures.FrontSquare extends src.frontend.front_figures.FrontRectangularFigure{
}
class src.frontend.front_figures.FrontCircle extends src.frontend.front_figures.FrontOvalFigure{
}
class src.frontend.front_figures.FrontEllipse extends src.frontend.front_figures.FrontOvalFigure{
}
@enduml